# version: '3.8'

# services:
#   app:
#     build: 
#       context: .
#     ports:
#       - 8000:8000
#     volumes:
#       - .:/djangoapp
#     image: app:djangoapi
#     container_name: djangoapi_container
#     command: python manage.py runserver 0.0.0.0:8000
version: '3'
services: 
  traderapi-deployment:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:80'


# # docker-compose build
# # docker-compose run app
# # docker-compose up -d --build
# # docker exec -it traderapi /bin/sh
