# version: '3.8'

# services:
#   app:
#     build: 
#       context: .
#     ports:
#       - 8000:8000
#     volumes:
#       - .:/djangoapp
#     image: app:djangoapi
#     container_name: djangoapi_container
#     command: python manage.py runserver 0.0.0.0:8000
#     depends_on:
#       - db

#   db:
#     image: postgres
#     volumes:
#       # - db_data:/var/lib/postgresql/data
#       - ./data/db:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=secret
#       - POSTGRES_USER=secret
#       - POSTGRES_PASSWORD=secret
#     container_name: postgres_db

# # docker-compose build
# # docker-compose run app
# # docker-compose up
# # docker-compose run rm app django-admin startproject core .
# # docker exec -it djangoapi_container /bin/bash
# # or
# # docker exec -it djangoapi_container /bin/sh
