# Generated by Django 4.2.2 on 2023-07-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email_forget_password', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
