# Generated by Django 4.2.2 on 2023-07-09 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_otp_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailotp',
            old_name='profile',
            new_name='user',
        ),
    ]
