# Generated by Django 4.2.2 on 2023-07-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_otp_auth', '0002_rename_profile_emailotp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='user',
        ),
    ]
