# Generated by Django 4.1.9 on 2023-06-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_profit', models.FloatField()),
                ('total_loss', models.FloatField()),
                ('highest_profit_trader', models.CharField(max_length=100)),
                ('lowest_profit_trader', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TraderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader', models.CharField(max_length=100)),
                ('profit_loss', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
