# Generated by Django 4.1.9 on 2023-06-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderdata',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
