# Generated by Django 4.1.9 on 2023-06-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_alter_traderdata_profit_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindashboarddata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
