# Generated by Django 4.1.9 on 2023-06-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0003_admindashboarddata_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderdata',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
