# Generated by Django 4.1.9 on 2023-06-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0005_alter_traderdata_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderdata',
            name='profit_loss',
            field=models.JSONField(default=list),
        ),
    ]
