# Generated by Django 4.1.9 on 2023-06-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0006_alter_traderdata_profit_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderdata',
            name='trader',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
